# Ping
GET http://localhost:8080/health

HTTP/1.1 200  - OK
content-type: application/json
vary: Origin
date: Tue, 30 Jun 2026 09:39:03 GMT
content-length: 51
connection: close
###
GET http://localhost:8080/metrics

HTTP/1.1 200  - OK
content-type: application/json
vary: Origin
date: Tue, 30 Jun 2026 09:39:05 GMT
content-length: 214
connection: close
###
POST http://localhost:8080/api/v1/members
Content-Type: application/json

{
    "birthday": "2029-04-30T10:30:05+07:00",
	"firstName": "required",
	"lastName": "required",
	"username": "required"
}

HTTP/1.1 400  - Bad Request
content-type: application/json
vary: Origin
date: Fri, 03 Jul 2026 10:08:18 GMT
content-length: 74
connection: close