# Ping
GET http://localhost:8080/health
###
GET http://localhost:8080/metrics
###
POST http://localhost:8080/api/v1/members
Content-Type: application/json

{
    "birthday": "2029-04-30T10:30:05+07:00",
	"firstName": "required",
	"lastName": "required",
	"username": "required"
}