// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package member

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockStorager creates a new instance of mockStorager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStorager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStorager {
	mock := &mockStorager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockStorager is an autogenerated mock type for the Storager type
type mockStorager struct {
	mock.Mock
}

type mockStorager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStorager) EXPECT() *mockStorager_Expecter {
	return &mockStorager_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockStorager
func (_mock *mockStorager) Create(ctx context.Context, member Member) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Member) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStorager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockStorager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - member Member
func (_e *mockStorager_Expecter) Create(ctx interface{}, member interface{}) *mockStorager_Create_Call {
	return &mockStorager_Create_Call{Call: _e.mock.On("Create", ctx, member)}
}

func (_c *mockStorager_Create_Call) Run(run func(ctx context.Context, member Member)) *mockStorager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Member
		if args[1] != nil {
			arg1 = args[1].(Member)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStorager_Create_Call) Return(err error) *mockStorager_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStorager_Create_Call) RunAndReturn(run func(ctx context.Context, member Member) error) *mockStorager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type mockStorager
func (_mock *mockStorager) GetAll(ctx context.Context) ([]Member, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Member, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Member); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockStorager_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type mockStorager_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockStorager_Expecter) GetAll(ctx interface{}) *mockStorager_GetAll_Call {
	return &mockStorager_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *mockStorager_GetAll_Call) Run(run func(ctx context.Context)) *mockStorager_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockStorager_GetAll_Call) Return(members []Member, err error) *mockStorager_GetAll_Call {
	_c.Call.Return(members, err)
	return _c
}

func (_c *mockStorager_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]Member, error)) *mockStorager_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type mockStorager
func (_mock *mockStorager) GetByUsername(ctx context.Context, username string) (Member, bool, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 Member
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Member, bool, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Member); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(Member)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, username)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockStorager_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type mockStorager_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *mockStorager_Expecter) GetByUsername(ctx interface{}, username interface{}) *mockStorager_GetByUsername_Call {
	return &mockStorager_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *mockStorager_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *mockStorager_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStorager_GetByUsername_Call) Return(member Member, b bool, err error) *mockStorager_GetByUsername_Call {
	_c.Call.Return(member, b, err)
	return _c
}

func (_c *mockStorager_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (Member, bool, error)) *mockStorager_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type mockStorager
func (_mock *mockStorager) Remove(ctx context.Context, username string) error {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStorager_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type mockStorager_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *mockStorager_Expecter) Remove(ctx interface{}, username interface{}) *mockStorager_Remove_Call {
	return &mockStorager_Remove_Call{Call: _e.mock.On("Remove", ctx, username)}
}

func (_c *mockStorager_Remove_Call) Run(run func(ctx context.Context, username string)) *mockStorager_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStorager_Remove_Call) Return(err error) *mockStorager_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStorager_Remove_Call) RunAndReturn(run func(ctx context.Context, username string) error) *mockStorager_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type mockStorager
func (_mock *mockStorager) Update(ctx context.Context, username string, member Member) error {
	ret := _mock.Called(ctx, username, member)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, Member) error); ok {
		r0 = returnFunc(ctx, username, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStorager_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockStorager_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - member Member
func (_e *mockStorager_Expecter) Update(ctx interface{}, username interface{}, member interface{}) *mockStorager_Update_Call {
	return &mockStorager_Update_Call{Call: _e.mock.On("Update", ctx, username, member)}
}

func (_c *mockStorager_Update_Call) Run(run func(ctx context.Context, username string, member Member)) *mockStorager_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 Member
		if args[2] != nil {
			arg2 = args[2].(Member)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockStorager_Update_Call) Return(err error) *mockStorager_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStorager_Update_Call) RunAndReturn(run func(ctx context.Context, username string, member Member) error) *mockStorager_Update_Call {
	_c.Call.Return(run)
	return _c
}
