// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package member

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockServicer creates a new instance of mockServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockServicer {
	mock := &mockServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockServicer is an autogenerated mock type for the Servicer type
type mockServicer struct {
	mock.Mock
}

type mockServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockServicer) EXPECT() *mockServicer_Expecter {
	return &mockServicer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockServicer
func (_mock *mockServicer) Create(ctx context.Context, member Member) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Member) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockServicer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockServicer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - member Member
func (_e *mockServicer_Expecter) Create(ctx interface{}, member interface{}) *mockServicer_Create_Call {
	return &mockServicer_Create_Call{Call: _e.mock.On("Create", ctx, member)}
}

func (_c *mockServicer_Create_Call) Run(run func(ctx context.Context, member Member)) *mockServicer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Member
		if args[1] != nil {
			arg1 = args[1].(Member)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockServicer_Create_Call) Return(err error) *mockServicer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockServicer_Create_Call) RunAndReturn(run func(ctx context.Context, member Member) error) *mockServicer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Member provides a mock function for the type mockServicer
func (_mock *mockServicer) Member(ctx context.Context, username string) (Member, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for Member")
	}

	var r0 Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Member, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Member); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(Member)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockServicer_Member_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Member'
type mockServicer_Member_Call struct {
	*mock.Call
}

// Member is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *mockServicer_Expecter) Member(ctx interface{}, username interface{}) *mockServicer_Member_Call {
	return &mockServicer_Member_Call{Call: _e.mock.On("Member", ctx, username)}
}

func (_c *mockServicer_Member_Call) Run(run func(ctx context.Context, username string)) *mockServicer_Member_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockServicer_Member_Call) Return(member Member, err error) *mockServicer_Member_Call {
	_c.Call.Return(member, err)
	return _c
}

func (_c *mockServicer_Member_Call) RunAndReturn(run func(ctx context.Context, username string) (Member, error)) *mockServicer_Member_Call {
	_c.Call.Return(run)
	return _c
}

// Members provides a mock function for the type mockServicer
func (_mock *mockServicer) Members(ctx context.Context) ([]Member, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Members")
	}

	var r0 []Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Member, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Member); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockServicer_Members_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Members'
type mockServicer_Members_Call struct {
	*mock.Call
}

// Members is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockServicer_Expecter) Members(ctx interface{}) *mockServicer_Members_Call {
	return &mockServicer_Members_Call{Call: _e.mock.On("Members", ctx)}
}

func (_c *mockServicer_Members_Call) Run(run func(ctx context.Context)) *mockServicer_Members_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockServicer_Members_Call) Return(members []Member, err error) *mockServicer_Members_Call {
	_c.Call.Return(members, err)
	return _c
}

func (_c *mockServicer_Members_Call) RunAndReturn(run func(ctx context.Context) ([]Member, error)) *mockServicer_Members_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type mockServicer
func (_mock *mockServicer) Remove(ctx context.Context, username string) error {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockServicer_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type mockServicer_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *mockServicer_Expecter) Remove(ctx interface{}, username interface{}) *mockServicer_Remove_Call {
	return &mockServicer_Remove_Call{Call: _e.mock.On("Remove", ctx, username)}
}

func (_c *mockServicer_Remove_Call) Run(run func(ctx context.Context, username string)) *mockServicer_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockServicer_Remove_Call) Return(err error) *mockServicer_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockServicer_Remove_Call) RunAndReturn(run func(ctx context.Context, username string) error) *mockServicer_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type mockServicer
func (_mock *mockServicer) Update(ctx context.Context, username string, member Member) error {
	ret := _mock.Called(ctx, username, member)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, Member) error); ok {
		r0 = returnFunc(ctx, username, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockServicer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockServicer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - member Member
func (_e *mockServicer_Expecter) Update(ctx interface{}, username interface{}, member interface{}) *mockServicer_Update_Call {
	return &mockServicer_Update_Call{Call: _e.mock.On("Update", ctx, username, member)}
}

func (_c *mockServicer_Update_Call) Run(run func(ctx context.Context, username string, member Member)) *mockServicer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 Member
		if args[2] != nil {
			arg2 = args[2].(Member)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockServicer_Update_Call) Return(err error) *mockServicer_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockServicer_Update_Call) RunAndReturn(run func(ctx context.Context, username string, member Member) error) *mockServicer_Update_Call {
	_c.Call.Return(run)
	return _c
}
