# Ping
GET http://localhost:8080/health

HTTP/1.1 200  - OK
content-type: application/json
vary: Origin
date: Wed, 17 Jun 2026 08:14:13 GMT
content-length: 51
connection: close
###
GET http://localhost:8080/metrics

HTTP/1.1 200  - OK
content-type: application/json
vary: Origin
date: Wed, 17 Jun 2026 08:14:14 GMT
content-length: 214
connection: close