// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package example

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockStorager creates a new instance of mockStorager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStorager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStorager {
	mock := &mockStorager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockStorager is an autogenerated mock type for the Storager type
type mockStorager struct {
	mock.Mock
}

type mockStorager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStorager) EXPECT() *mockStorager_Expecter {
	return &mockStorager_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type mockStorager
func (_mock *mockStorager) CreateUser(user User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStorager_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type mockStorager_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user User
func (_e *mockStorager_Expecter) CreateUser(user interface{}) *mockStorager_CreateUser_Call {
	return &mockStorager_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *mockStorager_CreateUser_Call) Run(run func(user User)) *mockStorager_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 User
		if args[0] != nil {
			arg0 = args[0].(User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockStorager_CreateUser_Call) Return(err error) *mockStorager_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStorager_CreateUser_Call) RunAndReturn(run func(user User) error) *mockStorager_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UserByName provides a mock function for the type mockStorager
func (_mock *mockStorager) UserByName(name string) (User, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for UserByName")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (User, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) User); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockStorager_UserByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByName'
type mockStorager_UserByName_Call struct {
	*mock.Call
}

// UserByName is a helper method to define mock.On call
//   - name string
func (_e *mockStorager_Expecter) UserByName(name interface{}) *mockStorager_UserByName_Call {
	return &mockStorager_UserByName_Call{Call: _e.mock.On("UserByName", name)}
}

func (_c *mockStorager_UserByName_Call) Run(run func(name string)) *mockStorager_UserByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockStorager_UserByName_Call) Return(user User, err error) *mockStorager_UserByName_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockStorager_UserByName_Call) RunAndReturn(run func(name string) (User, error)) *mockStorager_UserByName_Call {
	_c.Call.Return(run)
	return _c
}

// Users provides a mock function for the type mockStorager
func (_mock *mockStorager) Users() ([]User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Users")
	}

	var r0 []User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockStorager_Users_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Users'
type mockStorager_Users_Call struct {
	*mock.Call
}

// Users is a helper method to define mock.On call
func (_e *mockStorager_Expecter) Users() *mockStorager_Users_Call {
	return &mockStorager_Users_Call{Call: _e.mock.On("Users")}
}

func (_c *mockStorager_Users_Call) Run(run func()) *mockStorager_Users_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockStorager_Users_Call) Return(users []User, err error) *mockStorager_Users_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *mockStorager_Users_Call) RunAndReturn(run func() ([]User, error)) *mockStorager_Users_Call {
	_c.Call.Return(run)
	return _c
}
