// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package example

import (
	"github.com/kongsakchai/gotemplate/app"
	mock "github.com/stretchr/testify/mock"
)

// newMockStorager creates a new instance of mockStorager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStorager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStorager {
	mock := &mockStorager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockStorager is an autogenerated mock type for the Storager type
type mockStorager struct {
	mock.Mock
}

type mockStorager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStorager) EXPECT() *mockStorager_Expecter {
	return &mockStorager_Expecter{mock: &_m.Mock}
}

// UserByName provides a mock function for the type mockStorager
func (_mock *mockStorager) UserByName(name string) (User, app.Error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for UserByName")
	}

	var r0 User
	var r1 app.Error
	if returnFunc, ok := ret.Get(0).(func(string) (User, app.Error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) User); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) app.Error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(app.Error)
	}
	return r0, r1
}

// mockStorager_UserByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByName'
type mockStorager_UserByName_Call struct {
	*mock.Call
}

// UserByName is a helper method to define mock.On call
//   - name string
func (_e *mockStorager_Expecter) UserByName(name interface{}) *mockStorager_UserByName_Call {
	return &mockStorager_UserByName_Call{Call: _e.mock.On("UserByName", name)}
}

func (_c *mockStorager_UserByName_Call) Run(run func(name string)) *mockStorager_UserByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockStorager_UserByName_Call) Return(user User, error app.Error) *mockStorager_UserByName_Call {
	_c.Call.Return(user, error)
	return _c
}

func (_c *mockStorager_UserByName_Call) RunAndReturn(run func(name string) (User, app.Error)) *mockStorager_UserByName_Call {
	_c.Call.Return(run)
	return _c
}

// Users provides a mock function for the type mockStorager
func (_mock *mockStorager) Users() ([]User, app.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Users")
	}

	var r0 []User
	var r1 app.Error
	if returnFunc, ok := ret.Get(0).(func() ([]User, app.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() app.Error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(app.Error)
	}
	return r0, r1
}

// mockStorager_Users_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Users'
type mockStorager_Users_Call struct {
	*mock.Call
}

// Users is a helper method to define mock.On call
func (_e *mockStorager_Expecter) Users() *mockStorager_Users_Call {
	return &mockStorager_Users_Call{Call: _e.mock.On("Users")}
}

func (_c *mockStorager_Users_Call) Run(run func()) *mockStorager_Users_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockStorager_Users_Call) Return(users []User, error app.Error) *mockStorager_Users_Call {
	_c.Call.Return(users, error)
	return _c
}

func (_c *mockStorager_Users_Call) RunAndReturn(run func() ([]User, app.Error)) *mockStorager_Users_Call {
	_c.Call.Return(run)
	return _c
}
