basePath: /
consumes:
    - application/json
host: localhost:8080
info:
    description: Documentation of our Go Template API.
    title: Go Template.
    version: 1.0.0
paths:
    /health:
        get:
            operationId: none
            responses:
                "200":
                    $ref: '#/responses/healthResponse'
                "500":
                    $ref: '#/responses/errorDatabaseResponse'
            summary: Health check endpoint.
            tags:
                - common
    /metrics:
        get:
            operationId: none
            responses:
                "200":
                    $ref: '#/responses/metricsResponse'
            summary: Metrics endpoint.
            tags:
                - common
produces:
    - application/json
responses:
    errorDatabaseResponse:
        description: ""
        schema:
            properties:
                code:
                    example: "9998"
                    type: string
                    x-go-name: Code
                message:
                    example: database is not ready
                    type: string
                    x-go-name: Message
                success:
                    example: false
                    type: boolean
                    x-go-name: Success
            type: object
    errorInternalResponse:
        description: ""
        schema:
            properties:
                code:
                    example: "9999"
                    type: string
                    x-go-name: Code
                message:
                    example: internal error
                    type: string
                    x-go-name: Message
                success:
                    example: false
                    type: boolean
                    x-go-name: Success
            type: object
    healthResponse:
        description: ""
        schema:
            properties:
                code:
                    example: "0000"
                    type: string
                    x-go-name: Code
                message:
                    example: health
                    type: string
                    x-go-name: Message
                success:
                    example: true
                    type: boolean
                    x-go-name: Success
            type: object
    metricsResponse:
        description: ""
        schema:
            properties:
                code:
                    example: "0000"
                    type: string
                    x-go-name: Code
                data:
                    properties:
                        alloc:
                            description: |-
                                {
                                "code": "0000",
                                "success": true,
                                "data": {
                                "alloc": "0.77 MB",
                                "heapIdle": "2.34 MB",
                                "heapInuse": "1.38 MB",
                                "heapReleased": "2.28 MB",
                                "stackInuse": "0.28 MB",
                                "stackSys": "0.28 MB",
                                "sysAlloc": "8.02 MB",
                                "totalAlloc": "0.77 MB"
                                }
                                }
                            example: 0.77 MB
                            type: string
                            x-go-name: Alloc
                        heapIdle:
                            example: 2.34 MB
                            type: string
                            x-go-name: HeapIdle
                        heapInuse:
                            example: 1.38 MB
                            type: string
                            x-go-name: HeapInuse
                        heapReleased:
                            example: 2.28 MB
                            type: string
                            x-go-name: HeapReleased
                        stackInuse:
                            example: 0.28 MB
                            type: string
                            x-go-name: StackInuse
                        stackSys:
                            example: 0.28 MB
                            type: string
                            x-go-name: StackSys
                        sysAlloc:
                            example: 0.28 MB
                            type: string
                            x-go-name: SysAlloc
                        totalAlloc:
                            example: 0.28 MB
                            type: string
                            x-go-name: TotalAlloc
                    type: object
                    x-go-name: Data
                success:
                    example: true
                    type: boolean
                    x-go-name: Success
            type: object
schemes:
    - http
    - https
security:
    - key:
        - '[]'
securityDefinitions:
    key:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
