// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package todoapp

import (
	"context"

	"github.com/kongsakchai/gotemplate/internal/todo"
	mock "github.com/stretchr/testify/mock"
)

// newMockServicer creates a new instance of mockServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockServicer {
	mock := &mockServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockServicer is an autogenerated mock type for the Servicer type
type mockServicer struct {
	mock.Mock
}

type mockServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockServicer) EXPECT() *mockServicer_Expecter {
	return &mockServicer_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type mockServicer
func (_mock *mockServicer) CreateTodo(ctx context.Context, userID string, todo1 todo.Todo) error {
	ret := _mock.Called(ctx, userID, todo1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, todo.Todo) error); ok {
		r0 = returnFunc(ctx, userID, todo1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockServicer_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type mockServicer_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - todo1 todo.Todo
func (_e *mockServicer_Expecter) CreateTodo(ctx interface{}, userID interface{}, todo1 interface{}) *mockServicer_CreateTodo_Call {
	return &mockServicer_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx, userID, todo1)}
}

func (_c *mockServicer_CreateTodo_Call) Run(run func(ctx context.Context, userID string, todo1 todo.Todo)) *mockServicer_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 todo.Todo
		if args[2] != nil {
			arg2 = args[2].(todo.Todo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockServicer_CreateTodo_Call) Return(err error) *mockServicer_CreateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockServicer_CreateTodo_Call) RunAndReturn(run func(ctx context.Context, userID string, todo1 todo.Todo) error) *mockServicer_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type mockServicer
func (_mock *mockServicer) DeleteTodo(ctx context.Context, userID string, id string) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockServicer_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type mockServicer_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *mockServicer_Expecter) DeleteTodo(ctx interface{}, userID interface{}, id interface{}) *mockServicer_DeleteTodo_Call {
	return &mockServicer_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, userID, id)}
}

func (_c *mockServicer_DeleteTodo_Call) Run(run func(ctx context.Context, userID string, id string)) *mockServicer_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockServicer_DeleteTodo_Call) Return(err error) *mockServicer_DeleteTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockServicer_DeleteTodo_Call) RunAndReturn(run func(ctx context.Context, userID string, id string) error) *mockServicer_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodos provides a mock function for the type mockServicer
func (_mock *mockServicer) GetTodos(ctx context.Context, userID string) ([]todo.Todo, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTodos")
	}

	var r0 []todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]todo.Todo, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []todo.Todo); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]todo.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockServicer_GetTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodos'
type mockServicer_GetTodos_Call struct {
	*mock.Call
}

// GetTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockServicer_Expecter) GetTodos(ctx interface{}, userID interface{}) *mockServicer_GetTodos_Call {
	return &mockServicer_GetTodos_Call{Call: _e.mock.On("GetTodos", ctx, userID)}
}

func (_c *mockServicer_GetTodos_Call) Run(run func(ctx context.Context, userID string)) *mockServicer_GetTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockServicer_GetTodos_Call) Return(todos []todo.Todo, err error) *mockServicer_GetTodos_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *mockServicer_GetTodos_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]todo.Todo, error)) *mockServicer_GetTodos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type mockServicer
func (_mock *mockServicer) UpdateTodo(ctx context.Context, userID string, todo1 todo.Todo) error {
	ret := _mock.Called(ctx, userID, todo1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, todo.Todo) error); ok {
		r0 = returnFunc(ctx, userID, todo1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockServicer_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type mockServicer_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - todo1 todo.Todo
func (_e *mockServicer_Expecter) UpdateTodo(ctx interface{}, userID interface{}, todo1 interface{}) *mockServicer_UpdateTodo_Call {
	return &mockServicer_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, userID, todo1)}
}

func (_c *mockServicer_UpdateTodo_Call) Run(run func(ctx context.Context, userID string, todo1 todo.Todo)) *mockServicer_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 todo.Todo
		if args[2] != nil {
			arg2 = args[2].(todo.Todo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockServicer_UpdateTodo_Call) Return(err error) *mockServicer_UpdateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockServicer_UpdateTodo_Call) RunAndReturn(run func(ctx context.Context, userID string, todo1 todo.Todo) error) *mockServicer_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockVerifier creates a new instance of mockVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockVerifier {
	mock := &mockVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockVerifier is an autogenerated mock type for the Verifier type
type mockVerifier struct {
	mock.Mock
}

type mockVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockVerifier) EXPECT() *mockVerifier_Expecter {
	return &mockVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type mockVerifier
func (_mock *mockVerifier) Verify(tokenString string) (map[string]any, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]any, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]any); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type mockVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - tokenString string
func (_e *mockVerifier_Expecter) Verify(tokenString interface{}) *mockVerifier_Verify_Call {
	return &mockVerifier_Verify_Call{Call: _e.mock.On("Verify", tokenString)}
}

func (_c *mockVerifier_Verify_Call) Run(run func(tokenString string)) *mockVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockVerifier_Verify_Call) Return(stringToV map[string]any, err error) *mockVerifier_Verify_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *mockVerifier_Verify_Call) RunAndReturn(run func(tokenString string) (map[string]any, error)) *mockVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}
