// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package todo

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockStorager creates a new instance of mockStorager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStorager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStorager {
	mock := &mockStorager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockStorager is an autogenerated mock type for the Storager type
type mockStorager struct {
	mock.Mock
}

type mockStorager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStorager) EXPECT() *mockStorager_Expecter {
	return &mockStorager_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type mockStorager
func (_mock *mockStorager) CreateTodo(ctx context.Context, todo Todo) error {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Todo) error); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStorager_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type mockStorager_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todo Todo
func (_e *mockStorager_Expecter) CreateTodo(ctx interface{}, todo interface{}) *mockStorager_CreateTodo_Call {
	return &mockStorager_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx, todo)}
}

func (_c *mockStorager_CreateTodo_Call) Run(run func(ctx context.Context, todo Todo)) *mockStorager_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Todo
		if args[1] != nil {
			arg1 = args[1].(Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStorager_CreateTodo_Call) Return(err error) *mockStorager_CreateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStorager_CreateTodo_Call) RunAndReturn(run func(ctx context.Context, todo Todo) error) *mockStorager_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type mockStorager
func (_mock *mockStorager) DeleteTodo(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStorager_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type mockStorager_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockStorager_Expecter) DeleteTodo(ctx interface{}, id interface{}) *mockStorager_DeleteTodo_Call {
	return &mockStorager_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, id)}
}

func (_c *mockStorager_DeleteTodo_Call) Run(run func(ctx context.Context, id string)) *mockStorager_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStorager_DeleteTodo_Call) Return(err error) *mockStorager_DeleteTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStorager_DeleteTodo_Call) RunAndReturn(run func(ctx context.Context, id string) error) *mockStorager_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// FindTodo provides a mock function for the type mockStorager
func (_mock *mockStorager) FindTodo(ctx context.Context, userID string, id string) (Todo, bool, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindTodo")
	}

	var r0 Todo
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (Todo, bool, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) Todo); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, userID, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockStorager_FindTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTodo'
type mockStorager_FindTodo_Call struct {
	*mock.Call
}

// FindTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *mockStorager_Expecter) FindTodo(ctx interface{}, userID interface{}, id interface{}) *mockStorager_FindTodo_Call {
	return &mockStorager_FindTodo_Call{Call: _e.mock.On("FindTodo", ctx, userID, id)}
}

func (_c *mockStorager_FindTodo_Call) Run(run func(ctx context.Context, userID string, id string)) *mockStorager_FindTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockStorager_FindTodo_Call) Return(todo Todo, b bool, err error) *mockStorager_FindTodo_Call {
	_c.Call.Return(todo, b, err)
	return _c
}

func (_c *mockStorager_FindTodo_Call) RunAndReturn(run func(ctx context.Context, userID string, id string) (Todo, bool, error)) *mockStorager_FindTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodos provides a mock function for the type mockStorager
func (_mock *mockStorager) GetTodos(ctx context.Context, userID string) ([]Todo, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTodos")
	}

	var r0 []Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]Todo, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []Todo); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockStorager_GetTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodos'
type mockStorager_GetTodos_Call struct {
	*mock.Call
}

// GetTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockStorager_Expecter) GetTodos(ctx interface{}, userID interface{}) *mockStorager_GetTodos_Call {
	return &mockStorager_GetTodos_Call{Call: _e.mock.On("GetTodos", ctx, userID)}
}

func (_c *mockStorager_GetTodos_Call) Run(run func(ctx context.Context, userID string)) *mockStorager_GetTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStorager_GetTodos_Call) Return(todos []Todo, err error) *mockStorager_GetTodos_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *mockStorager_GetTodos_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]Todo, error)) *mockStorager_GetTodos_Call {
	_c.Call.Return(run)
	return _c
}

// HasUser provides a mock function for the type mockStorager
func (_mock *mockStorager) HasUser(ctx context.Context, userID string) (bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for HasUser")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockStorager_HasUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUser'
type mockStorager_HasUser_Call struct {
	*mock.Call
}

// HasUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockStorager_Expecter) HasUser(ctx interface{}, userID interface{}) *mockStorager_HasUser_Call {
	return &mockStorager_HasUser_Call{Call: _e.mock.On("HasUser", ctx, userID)}
}

func (_c *mockStorager_HasUser_Call) Run(run func(ctx context.Context, userID string)) *mockStorager_HasUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStorager_HasUser_Call) Return(b bool, err error) *mockStorager_HasUser_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockStorager_HasUser_Call) RunAndReturn(run func(ctx context.Context, userID string) (bool, error)) *mockStorager_HasUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type mockStorager
func (_mock *mockStorager) UpdateTodo(ctx context.Context, todo Todo) error {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Todo) error); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStorager_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type mockStorager_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todo Todo
func (_e *mockStorager_Expecter) UpdateTodo(ctx interface{}, todo interface{}) *mockStorager_UpdateTodo_Call {
	return &mockStorager_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, todo)}
}

func (_c *mockStorager_UpdateTodo_Call) Run(run func(ctx context.Context, todo Todo)) *mockStorager_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Todo
		if args[1] != nil {
			arg1 = args[1].(Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStorager_UpdateTodo_Call) Return(err error) *mockStorager_UpdateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStorager_UpdateTodo_Call) RunAndReturn(run func(ctx context.Context, todo Todo) error) *mockStorager_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}
