// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockStorager creates a new instance of mockStorager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStorager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStorager {
	mock := &mockStorager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockStorager is an autogenerated mock type for the Storager type
type mockStorager struct {
	mock.Mock
}

type mockStorager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStorager) EXPECT() *mockStorager_Expecter {
	return &mockStorager_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type mockStorager
func (_mock *mockStorager) CreateUser(ctx context.Context, user User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStorager_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type mockStorager_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user User
func (_e *mockStorager_Expecter) CreateUser(ctx interface{}, user interface{}) *mockStorager_CreateUser_Call {
	return &mockStorager_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *mockStorager_CreateUser_Call) Run(run func(ctx context.Context, user User)) *mockStorager_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 User
		if args[1] != nil {
			arg1 = args[1].(User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStorager_CreateUser_Call) Return(err error) *mockStorager_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStorager_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user User) error) *mockStorager_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function for the type mockStorager
func (_mock *mockStorager) FindUserByUsername(ctx context.Context, username string) (User, bool, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 User
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (User, bool, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, username)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockStorager_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type mockStorager_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *mockStorager_Expecter) FindUserByUsername(ctx interface{}, username interface{}) *mockStorager_FindUserByUsername_Call {
	return &mockStorager_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername", ctx, username)}
}

func (_c *mockStorager_FindUserByUsername_Call) Run(run func(ctx context.Context, username string)) *mockStorager_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStorager_FindUserByUsername_Call) Return(user User, b bool, err error) *mockStorager_FindUserByUsername_Call {
	_c.Call.Return(user, b, err)
	return _c
}

func (_c *mockStorager_FindUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (User, bool, error)) *mockStorager_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// newMockHasher creates a new instance of mockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockHasher {
	mock := &mockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockHasher is an autogenerated mock type for the Hasher type
type mockHasher struct {
	mock.Mock
}

type mockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHasher) EXPECT() *mockHasher_Expecter {
	return &mockHasher_Expecter{mock: &_m.Mock}
}

// ComparePassword provides a mock function for the type mockHasher
func (_mock *mockHasher) ComparePassword(pwd string, hash string) error {
	ret := _mock.Called(pwd, hash)

	if len(ret) == 0 {
		panic("no return value specified for ComparePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(pwd, hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockHasher_ComparePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComparePassword'
type mockHasher_ComparePassword_Call struct {
	*mock.Call
}

// ComparePassword is a helper method to define mock.On call
//   - pwd string
//   - hash string
func (_e *mockHasher_Expecter) ComparePassword(pwd interface{}, hash interface{}) *mockHasher_ComparePassword_Call {
	return &mockHasher_ComparePassword_Call{Call: _e.mock.On("ComparePassword", pwd, hash)}
}

func (_c *mockHasher_ComparePassword_Call) Run(run func(pwd string, hash string)) *mockHasher_ComparePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockHasher_ComparePassword_Call) Return(err error) *mockHasher_ComparePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockHasher_ComparePassword_Call) RunAndReturn(run func(pwd string, hash string) error) *mockHasher_ComparePassword_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function for the type mockHasher
func (_mock *mockHasher) HashPassword(pwd string) (string, error) {
	ret := _mock.Called(pwd)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(pwd)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(pwd)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pwd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockHasher_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type mockHasher_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - pwd string
func (_e *mockHasher_Expecter) HashPassword(pwd interface{}) *mockHasher_HashPassword_Call {
	return &mockHasher_HashPassword_Call{Call: _e.mock.On("HashPassword", pwd)}
}

func (_c *mockHasher_HashPassword_Call) Run(run func(pwd string)) *mockHasher_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockHasher_HashPassword_Call) Return(s string, err error) *mockHasher_HashPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockHasher_HashPassword_Call) RunAndReturn(run func(pwd string) (string, error)) *mockHasher_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSigner creates a new instance of mockSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSigner {
	mock := &mockSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockSigner is an autogenerated mock type for the Signer type
type mockSigner struct {
	mock.Mock
}

type mockSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSigner) EXPECT() *mockSigner_Expecter {
	return &mockSigner_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function for the type mockSigner
func (_mock *mockSigner) Sign(sub string, id string, extra map[string]any) (string, error) {
	ret := _mock.Called(sub, id, extra)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, map[string]any) (string, error)); ok {
		return returnFunc(sub, id, extra)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, map[string]any) string); ok {
		r0 = returnFunc(sub, id, extra)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, map[string]any) error); ok {
		r1 = returnFunc(sub, id, extra)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type mockSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - sub string
//   - id string
//   - extra map[string]any
func (_e *mockSigner_Expecter) Sign(sub interface{}, id interface{}, extra interface{}) *mockSigner_Sign_Call {
	return &mockSigner_Sign_Call{Call: _e.mock.On("Sign", sub, id, extra)}
}

func (_c *mockSigner_Sign_Call) Run(run func(sub string, id string, extra map[string]any)) *mockSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockSigner_Sign_Call) Return(s string, err error) *mockSigner_Sign_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockSigner_Sign_Call) RunAndReturn(run func(sub string, id string, extra map[string]any) (string, error)) *mockSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}
